name: SonicPay CI/CD pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  Testing:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Adjust the timeout as needed
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm install --prefix frontend 
      - run: npm start --prefix frontend & npx wait-on http://localhost:3000

      - name: Start Backend Server
        run: node backend/server.js &
        background: true  

      # Wait for the backend server to be ready
      - name: Wait for Backend Server
        run: npx wait-on http://localhost:4000


